### ISSUE TITLE
Research dual table database functionality

### ISSUE THREAD

**Issue by Drew26** [Drew26/MyKitchen#10]

**Comment by RMFogle** [comment]
My research: 
For dual tables in a database reference/check out the "Solved" folders for: 

Class-Content/12-mysql/01-Activities/14-TwoTables/Solved
Class-Content/14-handlebars/01-Activities/13-PartyDatabase/Solved
Class-Content/14handlebars/01-Activities/14-TheAsyncProblem/Solved
